version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ny_taxi
      POSTGRES_USER: ahona
      POSTGRES_PASSWORD: ahona
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ahona
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  postgres_data:
  pgadmin_data:
